CodeFramework/objects/Code_Kill_Switch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A set of checkboxes that let the admin turn off any logic elements implemented.</description>
    <fields>
        <fullName>Account_someRandomMethod__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account_someRandomMethod</label>
        <type>Checkbox</type>
    </fields>
    <label>Code Kill Switch</label>
</CustomObject>

CodeFramework/classes/AccountTriggerHandler.cls
/**
* @author       Jerun Jose Stanley @ Cloudwerx
* @description  Trigger handler for the Account object
*/
public class AccountTriggerHandler extends TriggerHandler{
    
    public override void onBeforeInsert(List<sObject> newRecords){
        if(UtilMethods.checkIfMethodEnabled(Code_Kill_Switch__c.Account_someRandomMethod__c))
        	someRandomMethod((List<Account>) newRecords, null);
    }
    
    private void someRandomMethod(List<Account> newRecords, Map<ID, Account> oldRecordsMap){
        String someConfigString = UtilMethods.apexConfigMap.get('someConfigString').Text_Value__c;
        UtilMethods.codeKillSwitch.Account_someRandomMethod__c = true;
    }
}